### ISSUE TITLE
Fix broken OV redirect links on Boston Local TV News in Firefox (2)

### ISSUE THREAD

**Issue by DraxIndustries79** [WGBH-MLA/bostonlocaltv#306]
**Describe the bug**
Broken redirect links from OV to Boston Local TV News in Firefox

https://openvault.wgbh.org/catalog/V_D857A536C39644378ECF9DC2A21A53E8

```[tasklist]
### Tasks
- [ ] Redirect links from OV -> BLTV not functioning
```

## Screencap

![Image](https://github.com/WGBH-MLA/bostonlocaltv/assets/37004183/96fb3f5b-cc2a-42cd-a0e1-89b777037847)

**Comment by foglabs** [comment]
Fixed - two things were causing this:

-'Outside URL' annotation on OV provided an http url:
`http://bostonlocaltv.org/catalog/V_4VU36AX5EIJOXH6`

Clicking this url in chrome automatically tries https first, and successfully accesses the desired page. Firefox instead actually navigates to the specified url `http://bostonlocaltv.org/catalog/V_4VU36AX5EIJOXH6`.

-boston local tv's apache config redirected http traffic to `https://bostonlocaltv.org` with no trailing slash, which then resolves to `https://bostonlocaltv.orgcatalog/V_4VU36AX5EIJOXH6`



Changed OV code to rewrite bltv external links to use https instead of http, and edited BLTV's apache config to include the trailing slash to fix the actual redirect problem:

```
<VirtualHost *:80>
   ServerName www.bostonlocaltv.org
   Redirect / https://bostonlocaltv.org/
</VirtualHost>
```


🦔💨
